name: Windows build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clone aquamarine repo
        run: git clone --branch ${{ github.head_ref }} https://github.com/MaksymT17/silber.git
        shell: bash

      - name: Build artifacts with Cmake
        run: |
          cd silber &&
          echo "removing existing build folder..."
          rm -rf build/ &&
          mkdir build &&
          echo "preparing new build with cmake..." &&
          cd build/ &&
          cmake .. &&
          cmake --build . &&
          echo "Build complete!"
        shell: bash
