name: Windows build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout aquamarine repo
        uses: actions/checkout@v3
        with:
          repository: MaksymT17/silber
          ref: ${{ github.head_ref }}  # Use the head reference of the pull request
          path: silber
          fetch-depth: 1  # Shallow clone

      - name: Build artifacts with Cmake
        run: |
          cd silber &&
          echo "removing existing build folder..."
          rm -rf build/ &&
          mkdir build &&
          echo "preparing new build with cmake..." &&
          cd build/ &&
          cmake .. &&
          cmake --build . --config Debug
        shell: bash

      - name: Run the binary
        run: |
          cd silber/build/Debug
          .\silber_test.exe
        shell: cmd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build-artifacts
          path: silber/build/Debug

  
